reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  ganache:
    verify: False
  mainnet-fork-dev:
    verify: False
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}